
data <- as.data.frame(fread("Normal tissue expression/rna_single_cell_type.csv"))
data <- data[,-1]

unique(data$`Cell type`)

# Create a named vector with the germ layer mappings
germ_layer <- c(
  "Adipocytes" = "Mesoderm",
  "Alveolar cells type 1" = "Endoderm",
  "Alveolar cells type 2" = "Endoderm",
  "Astrocytes" = "Ectoderm",
  "B-cells" = "Mesoderm",
  "Basal keratinocytes" = "Ectoderm",
  "Basal prostatic cells" = "Endoderm",
  "Basal respiratory cells" = "Endoderm",
  "Basal squamous epithelial cells" = "Ectoderm",
  "Bipolar cells" = "Ectoderm",
  "Breast glandular cells" = "Ectoderm",
  "Breast myoepithelial cells" = "Ectoderm",
  "Cardiomyocytes" = "Mesoderm",
  "Cholangiocytes" = "Endoderm",
  "Ciliated cells" = "Endoderm",
  "Club cells" = "Endoderm",
  "Collecting duct cells" = "Mesoderm",
  "Cone photoreceptor cells" = "Ectoderm",
  "Cytotrophoblasts" = "Trophoblast",
  "dendritic cells" = "Mesoderm",
  "Distal enterocytes" = "Endoderm",
  "Distal tubular cells" = "Mesoderm",
  "Ductal cells" = "Endoderm",
  "Early spermatids" = "Mesoderm",
  "Endometrial stromal cells" = "Mesoderm",
  "Endothelial cells" = "Mesoderm",
  "Enteroendocrine cells" = "Endoderm",
  "Erythroid cells" = "Mesoderm",
  "Excitatory neurons" = "Ectoderm",
  "Exocrine glandular cells" = "Endoderm",
  "Extravillous trophoblasts" = "Trophoblast",
  "Fibroblasts" = "Mesoderm",
  "Gastric mucus-secreting cells" = "Endoderm",
  "Glandular and luminal cells" = "Varies",
  "granulocytes" = "Mesoderm",
  "Granulosa cells" = "Mesoderm",
  "Hepatocytes" = "Endoderm",
  "Hofbauer cells" = "Mesoderm",
  "Horizontal cells" = "Ectoderm",
  "Inhibitory neurons" = "Ectoderm",
  "Intestinal goblet cells" = "Endoderm",
  "Ionocytes" = "Varies",
  "Kupffer cells" = "Mesoderm",
  "Langerhans cells" = "Mesoderm",
  "Late spermatids" = "Mesoderm",
  "Leydig cells" = "Mesoderm",
  "Lymphatic endothelial cells" = "Mesoderm",
  "Macrophages" = "Mesoderm",
  "Melanocytes" = "Ectoderm",
  "Mesothelial cells" = "Mesoderm",
  "Microglial cells" = "Mesoderm",
  "monocytes" = "Mesoderm",
  "Mucus glandular cells" = "Endoderm",
  "Muller glia cells" = "Ectoderm",
  "NK-cells" = "Mesoderm",
  "Oligodendrocyte precursor cells" = "Ectoderm",
  "Oligodendrocytes" = "Ectoderm",
  "Oocytes" = "Mesoderm",
  "Ovarian stromal cells" = "Mesoderm",
  "Pancreatic endocrine cells" = "Endoderm",
  "Paneth cells" = "Endoderm",
  "Peritubular cells" = "Mesoderm",
  "Plasma cells" = "Mesoderm",
  "Prostatic glandular cells" = "Endoderm",
  "Proximal enterocytes" = "Endoderm",
  "Proximal tubular cells" = "Mesoderm",
  "Rod photoreceptor cells" = "Ectoderm",
  "Salivary duct cells" = "Ectoderm",
  "Schwann cells" = "Ectoderm",
  "Secretory cells" = "Endoderm",
  "Serous glandular cells" = "Varies",
  "Sertoli cells" = "Mesoderm",
  "Skeletal myocytes" = "Mesoderm",
  "Smooth muscle cells" = "Mesoderm",
  "Spermatocytes" = "Mesoderm",
  "Spermatogonia" = "Mesoderm",
  "Squamous epithelial cells" = "Ectoderm",
  "Suprabasal keratinocytes" = "Ectoderm",
  "Syncytiotrophoblasts" = "Trophoblast",
  "T-cells" = "Mesoderm",
  "Undifferentiated cells" = "Varies"
)

data$origin <- germ_layer[data$`Cell type`]

fwrite(data, "Normal tissue expression/rna_single_cell_type_germ_layer.csv", row.names = T)
